[package]
name = "viewdock"
version = "0.1.0"
authors = ["Daniel Collin <daniel@collin.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "*"
syntex = "0.31.0"

[dependencies]
minifb = "0.6.0"
serde = "*"
serde_json = "*"

